/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolLogsRouteImport } from './routes/tool-logs'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const ToolLogsRoute = ToolLogsRouteImport.update({
  id: '/tool-logs',
  path: '/tool-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/tasks': typeof TasksRoute
  '/tool-logs': typeof ToolLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/tasks': typeof TasksRoute
  '/tool-logs': typeof ToolLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/tasks': typeof TasksRoute
  '/tool-logs': typeof ToolLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/documents' | '/login' | '/tasks' | '/tool-logs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/documents' | '/login' | '/tasks' | '/tool-logs'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/documents'
    | '/login'
    | '/tasks'
    | '/tool-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  TasksRoute: typeof TasksRoute
  ToolLogsRoute: typeof ToolLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool-logs': {
      id: '/tool-logs'
      path: '/tool-logs'
      fullPath: '/tool-logs'
      preLoaderRoute: typeof ToolLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  TasksRoute: TasksRoute,
  ToolLogsRoute: ToolLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
